name: html-tests
on:
  push:
    branches: [master]
    paths:
      - "lessons/test/**"
      - package.json
      - .github/workflows/html-tests.yml
jobs:
  run-tests:
    runs-on: ubuntu-22.04
    container:
      image: cypress/included:latest
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
      - name: Install ğŸ“¦
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          start: npm run dev -- --filter test-html
          wait-on: http://127.0.0.1:5500
      - name: Run Tests ğŸ§ª
        run: npm run test -- --filter test-html 
      # - name: Run Tests ğŸ§ª
      #   uses: cypress-io/github-action@v6
      #   with:
      #     working-directory: ./lessons/test
      #     install: false
      #     start: npm run dev
      #     wait-on: http://127.0.0.1:5500
