name: example-docker
on:
  push:
    branches:
      [master]
      # only run this workflow when something in the app-a changes
      # or in this workflow file
      # paths:
      #   - 'apps/app-a/**'
      #   - .github/workflows/app-a.yml

jobs:
  docker-browsers:
    runs-on: ubuntu-22.04
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     browser: [electron]
    # from https://hub.docker.com/r/cypress/browsers/tags
    container:
      image: cypress/included:latest
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
      # replace with the following for regular use:
      - uses: cypress-io/github-action@v6
        with:
          runTests: false
          start: npm run dev
          # working-directory: examples/basic
          # browser: ${{ matrix.browser }}
      - run: npm run test
